### ISSUE TITLE
Cannot install skpm with node 8.11.1 (LTS)

### ISSUE THREAD

**Issue by DanielApt** [skpm/skpm#154]
Currently using node v.8.11.1 (LTS) and I get the following error when running `npm install -g skpm`

**Error**
```
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/util/types'
npm ERR! A complete log of this run can be found in (ATTACHED BELOW)
```

**Log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'skpm' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose npm-session 09d9f21825edaf58
5 verbose stack Error: Cannot find module 'internal/util/types'
5 verbose stack     at Function.Module._resolveFilename (module.js:547:15)
5 verbose stack     at Function.Module._load (module.js:474:25)
5 verbose stack     at Module.require (module.js:596:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at evalmachine.<anonymous>:31:26
5 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
5 verbose stack     at Module._compile (module.js:652:30)
5 verbose stack     at Object.Module._extensions..js (module.js:663:10)
5 verbose stack     at Module.load (module.js:565:32)
5 verbose stack     at tryModuleLoad (module.js:505:12)
5 verbose stack     at Function.Module._load (module.js:497:3)
5 verbose stack     at Module.require (module.js:596:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/graceful-fs.js:3:27)
5 verbose stack     at Module._compile (module.js:652:30)
5 verbose stack     at Object.Module._extensions..js (module.js:663:10)
6 verbose cwd /Users/danielapt/Documents/github
7 verbose Darwin 15.6.0
8 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "skpm"
9 verbose node v8.11.1
10 verbose npm  v5.6.0
11 error code MODULE_NOT_FOUND
12 error Cannot find module 'internal/util/types'
13 verbose exit [ 1, true ]
```

**Comment by DanielApt** [comment]
FYI - worked with node v6.11.5
